CREATE DATABASE LIMPEZA;

USE LIMPEZA;

CREATE TABLE CLIENTE (
COD_CLIENTE int,
NOME_CLIENTES VARCHAR(100),
CPF VARCHAR(14),
CELULAR VARCHAR(18),
ENDERECO VARCHAR(250)
);

CREATE TABLE FUNCIONARIOS (
COD_FUNCIONARIOS int,
NOME_FUNCIONARIO VARCHAR(100),
CPF_FUNCIONARIO VARCHAR(14),
DATA_NASCIMENTO VARCHAR(10),
SALARIO VARCHAR(250)
);

CREATE TABLE PRODUTOS (
COD_PRODUTOS int,
NOME_PRODUTOS VARCHAR (100),
DESCRICAO VARCHAR (250),
QTDE VARCHAR (250),
VALOR VARCHAR (250)
);

CREATE TABLE ESTOQUE ( 
COD_ESTOQUE int,
NOME_PRODUTO VARCHAR (100),
POSICAO VARCHAR (10),
QTDE VARCHAR (250),
VALIDADE VARCHAR (10)
);

CREATE TABLE PEDIDOS (
COD_PEDIDOS int,
ID_PEDIDO VARCHAR(13),
HORARIO_ENTREGA VARCHAR (5),
VALOR_PEDIDO VARCHAR (250),
DESCRICAO VARCHAR (250)
);






