--  BANCO DE DADOS 
CREATE DATABASE REMOTERC;

USE REMOTERC;

SELECT DATABASE();

CREATE TABLE PRODUTOS (
CODIGO INT NOT NULL,
UNIDADE CHAR(3) NOT NULL,
DESCRICAO VARCHAR(30) NULL, 
VALOR_UNIT DECIMAL(7,2) NOT NULL,
PRIMARY KEY (CODIGO)
);
INSERT INTO PRODUTOS VALUES(1, 40, 'Coca-Cola', 8.00);
INSERT INTO PRODUTOS VALUES(2, 20, 'Nutella', 29.00);
INSERT INTO PRODUTOS VALUES(3, 60, 'Sorvete', 15.00);
 
SELECT * FROM PRODUTOS;

UPDATE PRODUTOS
SET VALOR_UNIT = 25.00
WHERE DESCRICAO = 'Nutella';
 
UPDATE PRODUTOS 
SET VALOR_UNIT = 6.00,
DESCRICAO = 'Coca Zero' 
WHERE CODIGO = 4;

UPDATE PRODUTOS SET VALOR_UNIT = VALOR_UNIT + (VALOR_UNIT * 0.1);

CREATE TABLE VENDEDOR ( 
CODIGO INT NOT NULL, 
NOME VARCHAR(20) NOT NULL, 
SALARIO DECIMAL (7,2) NOT NULL,
FSALARIAL CHAR(1) NOT NULL, 
PRIMARY KEY (CODIGO)
);

INSERT INTO VENDEDOR VALUES(1,'Duda', 1.500, 1);
INSERT INTO VENDEDOR VALUES(2,'Vivi', 1.200, 2);

SELECT * FROM VENDEDOR;

UPDATE VENDEDOR 
SET SALARIO = 3150.00
WHERE FSALARIAL = 1; 

UPDATE VENDEDOR 
SET SALARIO = SALARIO + (SALARIO * 0.10) 
WHERE FSALARIAL = 2;

UPDATE VENDEDOR 
SET SALARIO = 3500.00 
WHERE FSALARIAL = 3;

-- DELETAR VALORES 

DELETE FROM VENDEDOR 
WHERE SALARIO < 2500.00;

DELETE FROM PRODUTOS;

-- REGISTRO UNICO 
DELETE FROM PRODUTOS WHERE CODIGO = '01';

-- REGISTRO MULTIPLO 
DELETE FROM VENDEDOR WHERE FSALARIAL = 2; 

-- INTERVALO (OPERADOR AND)
DELETE FROM VENDEDOR WHERE FSALARIAL >=1 AND CODIGO<=2; 

-- ESVAZIANO A TABELA 
DELETE FROM CLIENTES;

TRUNCATE TABLE PRODUTOS;

