CREATE DATABASE EXEMPLO3;

USE EXEMPLO3;

CREATE TABLE CLIENTE (
COD_CLIENTE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_CLIENTE VARCHAR (100) NOT NULL,
CPF_CLIENTE VARCHAR (14) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
ESTADO CHAR(2) DEFAULT 'SP',
CELULAR VARCHAR (19) NOT NULL
);

CREATE TABLE PRODUTOS (
COD_PRODUTOS  INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
NOME_PRODUTOS VARCHAR (255) NOT NULL,
QTDE INT,
DESCRICAO VARCHAR (255), 
VALOR DECIMAL (7,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
COD_FORNECEDOR INT AUTO_INCREMENT NOT NULL,
NOME_FORNECEDOR VARCHAR (100) NOT NULL, 
CIDADE CHAR(2) DEFAULT 'SP',
CNPJ VARCHAR (18) NOT NULL, 
CELULAR VARCHAR (19) NOT NULL,
ENDERECO VARCHAR (100) NOT NULL,
PRIMARY KEY (COD_FORNECEDOR)
);

CREATE TABLE TEM (
COD_TEM INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
COD_FORNECEDOR INT, 
COD_PRODUTO INT,
FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTOS (COD_PRODUTOS),
FOREIGN KEY (COD_FORNECEDOR) REFERENCES FORNECEDORES (COD_FORNECEDOR)
);

-- CONSULTA DE TABELAS 
SELECT * FROM PESSOA_FISICA;

-- REMOÇÃO DE TABELAS 
DROP TABLE CLIENTE;
-- REMOÇÃO DE BANCO DE DADOS 
DROP DATABASE EXEMPLO3;

-- ALTERAÇÕES DE CAMPOS 
ALTER TABLE CLIENTES 
ADD SEXO CHAR(1);

ALTER TABLE CLIENTES 
DROP COLUMN SEXO;

ALTER TABLE CLIENTES 
RENAME TO PESSOAS_FISICAS;

ALTER TABLE PESSOA_FISICA
CHANGE CPF CPFP VARCHAR(30);

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN NOME_CLIENTE VARCHAR(150);

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN ESTADO CHAR(2) DEFAULT 'MG';

ALTER TABLE PESSOA_FISICA
MODIFY COLUMN COD_CLIENTE INT;

ALTER TABLE PESSOA_FISICA
ADD PRIMARY KEY (COD_CLIENTE);

-- ALTERAÇÕES 
-- ACRESCENTAR OS CAMPOS CIDADE EM PESSOA_FISICA
-- ALTERAR O CAMPO VALOR PRODUTOS PARA DECIMAL (7,2)
-- ACRESCENTAR O CAMPO CIDADE E ESTADO EM FORNECEDOR E DEFENIR 
-- O ESTADO COMO PADRÃO 'SP'

-- 1)
ALTER TABLE PESSOA_FISICA
ADD CIDADE VARCHAR(60);

-- 2)
ALTER TABLE PRODUTOS
MODIFY COLUMN VALOR DECIMAL (7,2);

-- 3)

ALTER  TABLE FORNECEDORES 
ADD CIDADE VARCHAR(60);

ALTER TABLE FORNECEDORES
ADD ESTADO CHAR(2) DEFAULT 'SP';










