CREATE DATABASE BIBLIOTECA;

USE BIBLIOTECA;

CREATE TABLE LIVROS (
ID INT PRIMARY KEY AUTO_INCREMENT,
TITULO VARCHAR(100),
ANO_PUBLICADO INT 
);

CREATE TABLE CLIENTES (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(100),
EMAIL VARCHAR(50)
);

-- ALTERAR 
ALTER TABLE LIVROS ADD GENERO VARCHAR(100);
ALTER TABLE CLIENTES ADD TELEFONE VARCHAR(50);

SELECT * FROM LIVROS;

INSERT INTO LIVROS (TITULO, ANO_PUBLICADO, GENERO)
VALUES ('O Pequeno Príncipe',1943, 'Literatura infantil');

INSERT INTO CLIENTES (NOME, EMAIL, TELEFONE)
VALUES ('Maria', 'maria123@gmail.com', '19 9 8007-3551' );

SELECT * FROM CLIENTES;

DELETE FROM Livros WHERE id = 1;
DELETE FROM Leitores WHERE id = 1;

