-- CRIAR BANCO DE DADOS 
CREATE DATABASE EXEMPLO2;

-- ATIVAR BANCO DE DADOS 
USE EXEMPLO2;

CREATE TABLE CLIENTES (
COD_CLIENTES INT,
NOME_CLIENTE VARCHAR(100),
CPF_CLIENTE VARCHAR(14),
CELULAR VARCHAR(18),
ENDERECO VARCHAR(255)
);

CREATE TABLE ESTOQUE (
COD_ESTOQUE INT,
NOME_PRODUTO VARCHAR(100), 
VALIDADE VARCHAR(10),
QTDE VARCHAR(250),
POSICAO VARCHAR(10)
);

CREATE TABLE PRODUTOS (
COD_PRODUTOS INT,
NOME_PRODUTO VARCHAR (100),
DESCRICAO VARCHAR (250),
VALOR VARCHAR (250),
QTDE VARCHAR(100)
);

CREATE TABLE FUNCIONARIO (
COD_FUNCIONARIO INT,
NOME_FUNCIONARIO VARCHAR (100),
CPF_FUNCIONARIO VARCHAR (14),
SALARIO VARCHAR (250),
DATA_NASCIMENTO VARCHAR (10)
);

-- CONSULTA DE TABELAS 
SELECT * FROM CLIENTES;
SELECT * FROM ESTOQUE;
SELECT * FROM PRODUTOS;
SELECT * FROM FUNCIONARIOS;

